### ISSUE TITLE
Test out BERTTopic to get meaningful topic segmentations of a query dataset 

### ISSUE THREAD

**Issue by Gautam-Rajeev** [Samagra-Development/ai-tools#291] opened 2024-02-02 12:17 UTC
## Goal: 
Get an accurate list  of topics (around 20 topics max) for an agri dataset of queries (has around 20k unique queries) using BERTTopic. Only the 'questioninEnglish' column is relevant for the analysis

## Description
Be able to segregate the given [dataset ](https://drive.google.com/file/d/1N8FrqFHSZ3uLLjNYGV39DvF3ucvH6vjt/view?usp=drive_link) into topics using BERTTopics. 
The veracity of the clusters are difficult to measure and currently will have to be observed manually and verified. 
Any suggestions to measure this better are welcome
 
One can also use simple TF-IDF, Topic2vec or LDA if they form better clusters. The sentences are just one sentence questions, not a paragraph.  
 

## Implementation Details 
It'll include the following : 
- This will just be Collab notebook for an analysis done
- If results are good, this will be used as a classification model for similar queries
- Intuitive clusters that may form (initial seeds if required) 
      - paddy pest management 
      - paddy seed selection 
      - how to cultivate ____ crop
      - pest management for ____ crop 
      - best variety of seed for ____ crop 
      - wheat cultivation practices 
      - Scheme available from the govt 
      - wheat management and cultivation 

**Anyone is welcome to begin work on the ticket, it'll not be assigned to anyone in particular initially. One can ask doubts and provide solutions through comments. Relevant points and ticket will be assigned to the best PR raised.**

## Other links 

[Medium ](https://medium.com/@nick-tan/topic-modeling-with-bertopic-a-cookbook-with-an-end-to-end-example-part-1-3ef739b8d9f8)

## Product Name
AI Tools

## Organization Name
SamagraX

## Domain
NA

## Tech Skills Needed
Python, BERT, ML

## Category
Feature

## Mentor(s)
@GautamR-Samagra 

## Complexity
Low

**Comment by vilol-04** [comment] 2024-02-02 12:29
I would like to work on the issue @GautamR-Samagra

**Comment by Gautam-Rajeev** [comment] 2024-02-02 12:31
@vilol-04  Thanks, have given access to all for the dataset.  Do raise comments/PR when you are able to get significant results.

**Comment by masterismail** [comment] 2024-02-04 03:35
Hi @GautamR-Samagra ! the cook book which you have mentioned [medium.](https://medium.com/@nick-tan/topic-modeling-with-bertopic-a-cookbook-with-an-end-to-end-example-part-1-3ef739b8d9f8) It's only for medium paid members.

**Comment by Gautam-Rajeev** [comment] 2024-02-05 05:37
> Hi @GautamR-Samagra ! the cook book which you have mentioned [medium.](https://medium.com/@nick-tan/topic-modeling-with-bertopic-a-cookbook-with-an-end-to-end-example-part-1-3ef739b8d9f8) It's only for medium paid members.

Oh sorry, their home [documentation ](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html) is also pretty instructive

**Comment by aish7iitkgp** [comment] 2024-02-05 14:58
I would like to work on this issue @GautamR-Samagra

**Comment by masterismail** [comment] 2024-02-06 16:55
> > Hi @GautamR-Samagra ! the cook book which you have mentioned [medium.](https://medium.com/@nick-tan/topic-modeling-with-bertopic-a-cookbook-with-an-end-to-end-example-part-1-3ef739b8d9f8) It's only for medium paid members.
> 
> Oh sorry, their home [documentation ](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html) is also pretty instructive


yeah ! While keeping that handy, I'm currently conducting an analysis [here](https://colab.research.google.com/drive/11lCENDznkHyXfpNMGWsM9jQsl6N90SY_?usp=sharing)
 and facing challenges with the names of government schemes and the presence of Hinglish. Any recommendations for preprocessing?

**Comment by TakshPanchal** [comment] 2024-02-07 06:26
Hey @GautamR-Samagra , I was doing EDA for the data [here](https://colab.research.google.com/drive/1rN5cBbkchQh0dI329ZSXnpQXZ2b6xDH1?usp=sharing). We could try different models but I think embedding model has to be fine-tuned first. So, I wondered  is there any bigger corpus of this type of texts where abbreviations are used in indian context?

**Comment by Gautam-Rajeev** [comment] 2024-02-07 06:47
@masterismail @TakshPanchal  have tried to [clean ](https://colab.research.google.com/drive/1osf2me-ubjc2-OMIa00TNht8LIJbsDDS?usp=sharing) up the queries a bit - remove the Odia questions at least. 


Have reshared the dataset here
[predicted_values3.csv](https://github.com/Samagra-Development/ai-tools/files/14190026/predicted_values3.csv)

For the short forms and names of scheme/fertilizer/pesticide.. will need the help of program team to get those word list. Will update here once I get that.

**Comment by emharsha1812** [comment] 2024-02-11 07:01
Hello!  @GautamR-Samagra If this issue is still open, i would like to work on it

**Comment by Gautam-Rajeev** [comment] 2024-02-13 05:02
We have some scheme names and pesticide names : 
Schemes 1:  [Link](https://docs.google.com/spreadsheets/d/13EolXTZkSAd2P9jaitMzons6-sjHb_AF5OwSLDSuxrY/edit?usp=sharing)
Schemes 2:  [Link](https://docs.google.com/spreadsheets/d/1qgkpGYsLX5-eBeDV_US6Z548M5piQzSWG4xMRHPXX7U/edit?usp=sharing)

Crop-pesticide mapping :  
[Expert Committee Recommendations _2021-22.pdf](https://github.com/Samagra-Development/ai-tools/files/14256306/Expert.Committee.Recommendations._2021-22.pdf)

These are not well structured names in a column as we want, but such is work :)
I'll try parsing and share a table version in 2 days. 


I tried clustering on my end [here ](https://colab.research.google.com/drive/1AC12MiYaAXIUjXlN_nV0merncpbMeJsA?usp=sharing) but while smaller clusters are coming fairly well formed, the bigger clusters are mixing scheme(PM-Kisan) and paddy pesticide queries which is not good for us.  


Update on own clustering attempt : 
On overall data, decent small clusters are being formed -  but the 'anomaly cluster' and the first 1-2 big clusters are bad. They mix scheme and paddy pest data which is not good. 

Also, looks like all the 'Hinglish' 'Odinglish' clusters somehow got clustered into one cluster for me 

In initial attempt, most clusters being formed around crop names- for a  crop (say wheat) - all questions like cultivation, pest questions got clustered. 
On the other hand, the attempt is actually all the types of questions being asked, like -
Example types : 
- I can see y symptoms on the crop x, what should I do 
- How do I cultivate the crop x
- what is the correct dosage for fertilizer x 
- crop x 
- how should I test my soil 

I want to find a finite list of such questions as above that cover 95% of queries. Maybe we need to do something else to get there. Any thoughts? @TakshPanchal @masterismail 


In my notebook, I also tried to remove all crop names (just used  hard-coded list of common crop names and replaced with 'crop) and reclustered to get these types of questions which gave me some better types but again ferilizer names, pest names are still there and the issue of big ugly clusters being formed is still there.

**Comment by smokeyScraper** [comment] 2024-03-16 06:45
Hello @GautamR-Samagra 
can you assign this issue to me would like to give it a try 
also where can I dm you?

**Comment by Gautam-Rajeev** [comment] 2024-03-16 13:46
> Hello @GautamR-Samagra can you assign this issue to me would like to give it a try also where can I dm you?

Discordid: gautam28
gmail: gautam@samagragovernance.in

**Comment by Gautam-Rajeev** [comment] 2024-03-16 13:54
Here is a list of common pest, pesticides to remove before clustering. 
[Uploading [Tables]Expert Committee Recommendations _2021-22 (1).pdf (1).xlsx…]()

**Comment by Naveenpoliasetty** [comment] 2024-03-17 13:03
Hey @GautamR-Samagra can I have try ?

**Comment by 1DevVrat1** [comment] 2024-03-21 09:53
Hello @GautamR-Samagra Sir.
I have worked on the above problem and I have also created a Google Colab Notebook comprising of the model that clusters the given queries into topics and gives back a new csv file.
Please inform me about the next step that I have to perform in order to get the ticket.

**Comment by smokeyScraper** [comment] 2024-03-22 21:06
> Here is a list of common pest, pesticides to remove before clustering. Uploading [Tables]Expert Committee Recommendations _2021-22 (1).pdf (1).xlsx…

this link redirects back to the same issue instead of any list of pesticides table.
I tried clustering with multiple vectorizer algos and also tried on 'recobo/agri-sentence-transformer', it seems like 'recobo/agri-sentence-transformer' is working better, I gotta try once more after replacing the pesticides names with some other keyword 
can you please share me any ideas how can I collect the common pesticides name, I checked the pdf that was provided but it had a lot of pesticide names (119 pages) extracting which seemed kinda hard.
I have also dm'ed you at discord, my id- smokey (smokey_d_scraper)

**Comment by Gautam-Rajeev** [comment] 2024-03-24 06:46
reuploading the excel. last one seems to be a broken link. Thanks @kartikbhtt7 

[[Tables]Expert Committee Recommendations _2021-22 (1).pdf (1).xlsx](https://github.com/Samagra-Development/ai-tools/files/14734710/Tables.Expert.Committee.Recommendations._2021-22.1.pdf.1.xlsx)

**Comment by Sameer-Pal** [comment] 2024-03-29 07:08
@GautamR-Samagra  is this issue still accepting PR,
Can i work upon that  ?

**Comment by aditisingh2912** [comment] 2024-04-06 19:58
Hi, I want to take up this task on Topic Modelling @GautamR-Samagra

**Comment by HasanZaigam** [comment] 2024-04-09 10:27
Hello @GautamR-Samagra, could you please assign me this issue? I'll work on it with the best approach and try to fix it as quickly as possible. Thank you.

**Comment by VatsShaurya** [comment] 2024-05-06 06:52
Hello @GautamR-Samagra, Is this issue still open? I want to work on it. My understanding of the problem is that we have to classify the question into 20 different agricultural topics then we can form clusters according to it. 

My approach is to use a large language model like gpt-3.5-turbo for the multi-class classification - few shot. I will try achieving this if you will let me know.

Thank you

**Closed as completed** 2024-05-06 07:11 UTC
Labels: ai, C4GT Community

**Comment by Gautam-Rajeev** [comment] 2024-05-06 07:15
> Hello @GautamR-Samagra, Is this issue still open? I want to work on it. My understanding of the problem is that we have to classify the question into 20 different agricultural topics then we can form clusters according to it.
> 
> My approach is to use a large language model like gpt-3.5-turbo for the multi-class classification - few shot. I will try achieving this if you will let me know.
> 
> Thank you

this is closed for now [here](https://github.com/Samagra-Development/ai-tools/pull/316)

**Comment by Gautam-Rajeev** [comment] 2024-05-20 10:24
This issue has been closed by PR #316

**Comment by AkUp007** [comment] 2025-04-16 18:37
@Gautam-Rajeev could you please assign me this issue ?
